/**
 ******************************************************************************
 * @file    error_codes.h
 * @author  Aditya Mall,
 * @brief   Example MQTT publish client, for mosquitto MQTT Broker
 *
 *  Info
 *          Only for testing, (POSIX compatible only.)
 *
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; COPYRIGHT(c) 2019 Aditya Mall </center></h2>
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#ifndef ERROR_CODES_H_
#define ERROR_CODES_H_



/**/
enum error_codes
{
	FUNC_CODE_SUCCESS    =  0,
	CLIENT_INIT_ERROR    = -1,
	COMMAND_NO_ARGS      = -2,
	COMMAND_WRONG_ARGS   = -3,
	CLIENT_DESCRP_ERROR  = -4,
	SERVER_PORT_ERROR    = -5,
	SERVER_ADDRESS_ERROR = -6,
	CLIENT_DEINIT_ERROR  = -7,
	CLIENT_SOCKET_ERROR  = -8,
	CLIENT_CONNECT_ERROR = -9,
	COMMAND_LESS_ARGS    = -10,
	ADDRESS_LENGTH_ERROR = -11,
	TOPIC_LENGTH_ERROR   = -12,
	QOS_ERROR            = -13,
	NO_MESSAGE_ERROR     = -14,
	HELP_REQUEST         = -15,
	NO_TOPIC_NAME        = -16,
	KEEP_ALIVE_ERROR     = -17,
	BROKER_PORT_ERROR    = -18,

};




#endif /* MQTT_3_1_C_EXAMPLES_PUBLISHER_ERROR_CODES_H_ */
